export const EventsPublicFields = {
  organizationId: 1,
  name: 1,
  description: 1,
  regionName: 1,
  region: 1,
  startTime: 1,
  endTime: 1,
  webSiteUrl: 1,
  photoUrl: 1,
  invitationToken: 1,
  verifyGpsPositionsOfEdits: 1,
  targets: 1,
  status: 1,
  visibility: 1,
};
